### ISSUE TITLE
How can I find the paper link? Best regards!

### ISSUE THREAD

**Issue by SHU-FLYMAN** [Reallyhardtocreateaname/PhD-Thesis-Projects#2]
Dear Dr. Liu,
Your work is fantastic, but I can't find a link to your PhD thesis. As an rookie  to research reinforcement learning + intelligent scheduling, I feel that there is no way to start. Can you give me a link to your PhD thesis? Thank you very much!

Best regards!

email:    fly_cjb@163.com

**Comment by Reallyhardtocreateaname** [comment]
Hi, please refer to: https://www.tandfonline.com/doi/full/10.1080/00207543.2022.2058432  for the publication of DRL-based FJSP solution.

My PhD thesis is under embargo due to the pending publication of part of its content, if you're still interested in the JSP part, I can share the link once the paper is published. Which could happen in the next 3 months.

**Comment by SHU-FLYMAN** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    very thinks, Looking forward to your work！
    
    
     
    
        
                    
        
    
 

    On 5/13/2022 ***@***.***> wrote： 



Hi, please refer to: https://www.tandfonline.com/doi/full/10.1080/00207543.2022.2058432  for the publication of DRL-based FJSP solution.
My PhD thesis is under embargo due to the pending publication of part of its content, if you're still interested in the JSP part, I can share the link once the paper is published. Which could happen in the next 3 months.
